#### Numpy

- Numpy stands for numerical Python

- Fundamental package for numerical computation in python

- It has a large collection of high-level mathematical functions

- Fully supports OOP,Extensively used in Data Analysis

- Numpy is widely used in machine learning,it forms base of other libraries like scikit-learn

- Numpy array are of two types:
  
  a)Vector -> 1-Dimensional array
  
  b)Matrices -> 2-Dimensional array

#### To install Numpy

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [3]:
import numpy as np

In [4]:
l=[1,2,3,4,5]
arr1=np.array(l)
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
type(arr1).__name__

'ndarray'

In [7]:
arr1.shape

(5,)

In [8]:
arr1.size

5

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.ndim

1

In [12]:
ll=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(ll)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2.shape

(3, 3)

In [14]:
arr2.size

9

In [15]:
arr2.dtype

dtype('int32')

In [16]:
arr2.ndim

2

###  Built-in methods to create numpy arrays

#### arange
- np.arange(start:stop:step)
- By default,start=0, step=1, stop=n-1 (upper bound is excluded)

In [17]:
np.arange(25) # upper bound is excluded

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 0's and 1's

#### 0's

In [24]:
np.zeros(3) 

array([0., 0., 0.])

In [25]:
np.zeros((3,))

array([0., 0., 0.])

In [26]:
np.zeros(3,dtype='int') # 1-dimensional array

array([0, 0, 0])

In [30]:
np.zeros((3,2),dtype='int') # 2-dimensional array

array([[0, 0],
       [0, 0],
       [0, 0]])

#### 1's

In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones((3,))

array([1., 1., 1.])

In [34]:
np.ones(3,dtype='int') # 1-dimensional array

array([1, 1, 1])

In [35]:
np.ones((3,2),dtype='int') # 2-dimensional array

array([[1, 1],
       [1, 1],
       [1, 1]])

#### linspace
- np.linspace(start:stop:num)
- upper bound is included

In [39]:
np.linspace(1,10) # by default, num=50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [43]:
np.linspace(1,10,4,dtype='int') # start:stop:num

array([ 1,  4,  7, 10])

#### identity matrix
- no.of.rows=no.of.columns
- All elements are 0's except diagonal 1's


In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Random

#### rand
- uniform distribution
- 0 to 1

In [46]:
np.random.rand(3) # 1-dimensional array

array([0.63050519, 0.36346436, 0.05113325])

In [55]:
np.random.rand(2,3) # 2-dimensional array

array([[0.25656558, 0.27390596, 0.22289042],
       [0.8238597 , 0.65859373, 0.74068214]])

#### randn
- Standard Normal Distribution
- Normal Distribution with mean=0 and std=1

In [56]:
np.random.randn(3)  # 1-dimensional array

array([-1.99465306,  0.91264366, -0.59198557])

In [57]:
np.random.randn(2,3) # 2-dimensional array

array([[-1.25498094, -0.18956366,  1.4737948 ],
       [-1.24092263, -0.07971972,  1.4253278 ]])

#### randint

In [58]:
np.random.randint(100) # upper bound is excluded

18

In [59]:
np.random.randint(1,100,10) # 1-dimensional array

array([27, 16,  2, 79, 81,  7, 35,  7, 52, 85])

In [60]:
np.random.randint(1,100,(2,3)) # 2-dimensional array

array([[67, 62, 98],
       [38, 88, 56]])

#### Broadcasting

#### without copy

In [61]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
b=a[:2]
b

array([0, 1])

In [64]:
b[:]=100
b

array([100, 100])

In [65]:
a

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9])

- Please note that the changes in the subset (b) has affected the original array (a) as well
- Data is not copied when we subset, it is a sub-view of the original array
- This is a feature by default in order to avoid memory problems

#### with copy

In [70]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b=a[:2].copy()
b

array([0, 1])

In [72]:
b[:]=100
b

array([100, 100])

In [73]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### indexing and selection

#### 1-dimensional array

In [84]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a[::-1] # reverse a array

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a[0] # indexing

1

In [91]:
a[-1] # reverse indexing

9

In [92]:
a[1:4] # upper bound is excluded

array([2, 3, 4])

In [93]:
a[:3]

array([1, 2, 3])

In [94]:
a[3:]

array([4, 5, 6, 7, 8, 9])

In [95]:
a[::2]

array([1, 3, 5, 7, 9])

#### 2-dimensional array

The general formats used are

#### sample_matrix[row][col]

or

#### sample_matrix[row,col]

In [96]:
arr=np.random.randint(1,100,(4,5))
arr

array([[20, 29,  8, 25, 12],
       [89, 71, 62, 75, 30],
       [46, 49, 83, 74, 67],
       [56, 37, 34, 80, 89]])

In [97]:
arr[0][1]

29

In [98]:
arr[0,1]

29

In [99]:
arr[2][2]

83

In [100]:
arr[2,2]

83

In [101]:
arr[2:,3:]

array([[74, 67],
       [80, 89]])

In [102]:
arr

array([[20, 29,  8, 25, 12],
       [89, 71, 62, 75, 30],
       [46, 49, 83, 74, 67],
       [56, 37, 34, 80, 89]])

In [103]:
arr[1:3,:2]

array([[89, 71],
       [46, 49]])

In [105]:
arr[1:3,[1,3]]

array([[71, 75],
       [49, 74]])

##### max,min,argmax,argmin

In [115]:
arr=np.random.randint(1,100,10)
arr

array([30, 43, 87, 95, 76, 67, 14,  5, 45,  2])

In [116]:
arr.max()

95

In [117]:
arr.min()

2

In [118]:
arr.argmax()

3

In [119]:
arr.argmin()

9

#### conditional selection

In [120]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
arr[arr<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr[(arr>6) & (arr<12)]

array([ 7,  8,  9, 10, 11])

In [128]:
arr[(arr==6) | (arr==20)]

array([6])

##### Note:
- single value 'and'
- single value 'or'
- multiple values 
- or '|'
- and '&'

#### shape and re-shape

In [130]:
arr=np.random.randint(1,100,20)
arr

array([44, 84, 19, 47,  3, 95, 62, 40, 70,  1, 20, 90, 25, 60, 76, 90, 95,
       61,  6, 53])

In [131]:
arr.shape

(20,)

In [132]:
arr.reshape(4,5)

array([[44, 84, 19, 47,  3],
       [95, 62, 40, 70,  1],
       [20, 90, 25, 60, 76],
       [90, 95, 61,  6, 53]])

##### np.where

In [133]:
arr

array([44, 84, 19, 47,  3, 95, 62, 40, 70,  1, 20, 90, 25, 60, 76, 90, 95,
       61,  6, 53])

In [145]:
np.where(arr==19)

(array([2], dtype=int64),)

#### Arithmetic operations

In [146]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [148]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [149]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [150]:
arr/arr

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [151]:
arr//arr

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\3990451985.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [152]:
1/arr

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [154]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [155]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [156]:
pow(arr,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [157]:
pow(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

#### Universal array functions

In [158]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [160]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [161]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [162]:
np.log(arr)

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [163]:
np.log2(arr)

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\1405652587.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [164]:
np.log10(arr)

C:\Users\Tamilselvan.E\AppData\Local\Temp\ipykernel_6260\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [165]:
np.max(arr)

9

In [166]:
np.min(arr)

0

In [167]:
np.argmax(arr)

9

In [168]:
np.argmin(arr)

0

In [169]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [170]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [171]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [176]:
arr1=np.random.randn(3,2)
arr1

array([[-1.00410993,  1.49844243],
       [ 1.01175835,  0.44139788],
       [ 0.1177471 , -0.44922817]])

In [177]:
np.round(arr1)

array([[-1.,  1.],
       [ 1.,  0.],
       [ 0., -0.]])

In [178]:
np.round(arr1,decimals=2)

array([[-1.  ,  1.5 ],
       [ 1.01,  0.44],
       [ 0.12, -0.45]])

In [179]:
np.mean(arr1)

0.2693346100682336

In [180]:
np.std(arr1)

0.8418706393057093

In [181]:
np.var(arr1)

0.7087461733250037

In [182]:
0.84**2

0.7055999999999999

In [183]:
np.sqrt(0.7087461733250037)

0.8418706393057093

#### unique

In [184]:
sports=np.array(['Golf', 'Cricket', 'Football', 'Football','Cricket','cricket','Basketball', 'Baseball'])
sports

array(['Golf', 'Cricket', 'Football', 'Football', 'Cricket', 'cricket',
       'Basketball', 'Baseball'], dtype='<U10')

In [185]:
np.unique(sports)

array(['Baseball', 'Basketball', 'Cricket', 'Football', 'Golf', 'cricket'],
      dtype='<U10')

##### in1d

In [186]:
np.in1d(['Hockey','Cricket','Football'],sports)

array([False,  True,  True])

#### Numpy - Array input and output

In [192]:
a=arr

In [193]:
b=pow(a,2)

In [194]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### .npy

In [196]:
np.save('array1',a)

In [198]:
np.load('array1.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### .npz

In [199]:
np.savez('array2',a=a,b=b)

In [202]:
np.load('array2.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
np.load('array2.npz')['b']

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### .txt

In [206]:
np.savetxt('array3',a,delimiter=',')

In [207]:
np.loadtxt('array3',delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])